#pragma once
#include <memory>

namespace mlir {
class Pass;
class DialectRegistry;
}

namespace npux {
// Register all NPUX transform passes with the global PassRegistry.
void registerNpuxTransformPasses();

// Factory for the outline pass (generated by TableGen declaration).
std::unique_ptr<mlir::Pass> createOutlineNpuxOpsPass();
}
